#!/usr/bin/env bash

#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local url_vault_Darwin='https://releases.hashicorp.com/vault/0.5.0/vault_0.5.0_darwin_amd64.zip'
  local url_vault_Linux='https://releases.hashicorp.com/vault/0.5.0/vault_0.5.0_linux_amd64.zip'

  local url_vault="url_vault_$(uname -s)"
  local fnm_vault="$(basename "${!url_vault}")"
  cache curl "$fnm_vault" "${!url_vault}"
  
  pushd bin
  unzip -o "${BASEBOX_CACHE}/curl/$fnm_vault"
  chmod 755 vault
  popd
}

bootstrap
