#!/usr/bin/env bash

function version {
  local shome="${_vault_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  local ver_vault="$(vault --version 2>&- | awk '{print $2}' | perl -pe 's{^v}{}' || true)"
  jq -n --arg vault "$ver_vault" '{vault: $vault}'
}

version "$@"
